export const GuestUrl = "https://www.reetro.app/board/6343aae05465136fe0c01c5b/639828fe9af521a4328bd447"
export const BaseUrl = `https://reetro-io-staging.herokuapp.com/`
export const ProductionURL = 'https://www.reetro.app/'
export const GuestURLProduc ='https://www.reetro.app/board/6407200daba228540fb420c2/6423cf0bd8df55a1128daa75'
export const stagingadmin = 'mahrukh.loxvo13@gmail.com'
export const passwrdstag = 'test1234'
export const productionpaswd = 'test1234'
export const producAdmin = 'mahrukh.loxvo13+jack@gmail.com'
export const email_field = '[placeholder="Email"]'
export const guest_emailF= '.sign-form-field'
export const Password_field = '[placeholder="Password"]'
export const Login_Button = '.login-signup-button'
export const ToastMsg = '.toast-message.warning'
export const ForgotPaswrd = '.forgot-pwd'
export const SelectCompany= ':nth-child(3) > .team-box-button'
export const FeedbackBthn = '.sidebar-item'
export const SendFeedBack = '.button-primary'
export const SelectAssignee = '.pos-rel > .sb-avatar > .ticket-user-pic'
export const SuccessMsg = ".toast-message.success"
export const FeedBackTitle = '.give-feedback-title'
export const FeedbackDetails = '.give-feedback-detail'
export const Send_Request_FeedBtn = '.justify-content-end > .button-primary'
export const RequestFeedback = '.button-primary-outline'
export const NewBoard  = '.mh-new-board-icon-grid'
export const CustomTempBoard = '.create-new-template-box'
export const BoardTitle = '[type="text"]'
export const BoardDescription = '.cf-textarea'
export const boardType = '.reetro-select__control'
export const PublicBoardToggle = ':nth-child(12) > .cf-switch > .toggle-switch > .switch > .slider'
export const MaskCommentToggle = ':nth-child(13) > .cf-switch > .toggle-switch > .switch > .slider'
export const RUnanonmyoustoggle = ':nth-child(14) > .cf-switch > .toggle-switch > .switch > .slider'
export const SaveAsTemplateBoard = ':nth-child(16) > .cf-switch > .toggle-switch > .switch > .slider'
export const BoardTempName = '.mt-2'
export const CreateBoardBtn = '.create-board-btn'
export const guestscrnCheckmark = '.checkmark'
export const GuestSignBtn = '.field-box-signin > :nth-child(3)'
export const BoardSetting = '.share-btn'