name: Reetro End To End Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Cypress run
        uses: cypress-io/github-action@v3
       
      - uses: actions/upload-artifact@v3
        if : failure()
        with:
           name : cypress-screenshots
           path: cypress/screenshots
           
      #Test run videos was always captured, so ths action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
           name : cypress-videos
           path: cypress-vidoes     